# Generated by Django 5.1 on 2024-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='trace',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='positionaction',
            name='trace',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sltporder',
            name='trace',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='trace',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
